import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { DockWrapper } from "@/components/DockWrapper";
import { Toaster } from "@/components/ui/sonner";
import PageLoader from "@/components/PageLoader";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${inter.variable} ${poppins.variable}`}>
        <AuthProvider />
        <PageLoader />
        {children}
        <Toaster />
        <DockWrapper />
      </body>
    </html>
  );
}
