import {
  Wifi,
  Car,
  Utensils,
  Dumbbell,
  Tv,
  AirVent,
  Shirt,
  Coffee,
  Users,
  Shield,
  BrushIcon as BrushCleaning,
  Camera,
  Zap,
  Droplets,
  Sofa,
  Bed,
  Refrigerator,
  BookOpen,
  Lightbulb,
  Home,
  Bath,
} from "lucide-react";
import type { PGFormData, ValidationErrors } from "./types";

export const predefinedAmenities = [
  { id: "wifi", label: "Wi-Fi", icon: Wifi },
  { id: "ac", label: "Air Conditioning", icon: AirVent },
  { id: "geyser", label: "Geyser", icon: Zap },
  { id: "water-purifier", label: "Water Purifier", icon: Droplets },
  { id: "laundry", label: "Laundry Facility", icon: Shirt },
  { id: "housekeeping", label: "Housekeeping", icon: BrushCleaning },
  { id: "cctv", label: "CCTV", icon: Camera },
  { id: "combined-cooking", label: "Combined Cooking area", icon: Coffee },
  { id: "common-area", label: "Common Area / Lounge", icon: Users },
  { id: "study-desk", label: "Study Desk", icon: BookOpen },
  { id: "mattress-wardrobe", label: "Mattress and Wardrobe", icon: Bed },
  {
    id: "common-refrigerator",
    label: "Common Refrigerator",
    icon: Refrigerator,
  },
  {
    id: "separate-refrigerator",
    label: "Separate Refrigerator",
    icon: Refrigerator,
  },
  { id: "gym", label: "GYM", icon: Dumbbell },
  { id: "power-backup", label: "Power backup", icon: Zap },
  { id: "library", label: "Library", icon: BookOpen },
  { id: "parking", label: "Parking", icon: Car },
  { id: "meals", label: "Meals", icon: Utensils },
  { id: "24x7-security", label: "24x7 Security", icon: Shield },
  { id: "tv", label: "TV/Entertainment", icon: Tv },
];

export const propertyTypes = [
  {
    id: "hostels",
    label: "Hostels",
    subTypes: [],
  },
  {
    id: "flats",
    label: "Flats",
    subTypes: [
      { id: "1bhk", label: "1 BHK" },
      { id: "2bhk", label: "2 BHK" },
      { id: "3bhk", label: "3 BHK" },
    ],
  },
  {
    id: "pgs",
    label: "PGs",
    subTypes: [],
  },
  {
    id: "rooms",
    label: "Rooms",
    subTypes: [
      { id: "single-room", label: "Single Room" },
      { id: "1rk", label: "1 RK" },
    ],
  },
  {
    id: "commercial",
    label: "Commercial Properties",
    subTypes: [
      { id: "office-space", label: "Office Space" },
      { id: "shop", label: "Shop/Retail" },
      { id: "warehouse", label: "Warehouse" },
      { id: "restaurant", label: "Restaurant" },
      { id: "clinic", label: "Medical Clinic" },
    ],
  },
];

export const initialErrors: ValidationErrors = {
  pgName: false,
  monthlyRent: false,
  additionalDetails: false,
  rulesAndRegulations: false,
  images: false,
  videos: false,
  area: false,
  city: false,
  state: false,
  pincode: false,
  coordinates: false,
  latitude: false,
  longitude: false,
  general: "",
  securityDeposit: false,
  numberOfRooms: false,
  capacityPerRoom: false,
  genderPreference: false,
};

export const initialFormData: PGFormData = {
  id: "",
  pgName: "",
  type: "",
  subType: "",
  roomTypes: [
    {
      type: "",
      numberOfRooms: 0,
      capacityPerRoom: 0,
      monthlyRent: 0,
      securityDeposit: 0,
    },
  ],
  genderPreference: "both",
  additionalDetails: [],
  additionalDetailsInput: "",
  location: {
    area: "",
    city: "",
    state: "",
    pincode: "",
    nearbyPlaces: [],
    nearbyPlacesInput: "",
    coordinates: { lat: 30.7333, lng: 76.7794 },
  },
  rulesAndRegulations: [],
  newRuleInput: "",

  // Enhanced Rules Structure
  detailedRules: {
    lockInPeriod: "",
    noticePeriod: "",
    maintenanceCharges: "",
    entryTiming: "",
    exitTiming: "",
    guestStayPolicy: "",
    smokingAlcoholPolicy: "",
  },
  images: [],
  existingImageUrls: [],
  videos: [],
  existingVideoUrls: [],
  amenities: [],
  customAmenities: "",
  foodIncluded: false,
  electricityIncluded: false,
  maintenanceIncluded: false,
  // New fields for payment
  planType: "free",
  paymentStatus: "pending",
  paymentId: "",
  paymentProof: "",
  // paymentProof: File,
};

export const stepTitles = {
  1: "Basic Information",
  2: "Location",
  3: "Amenities & Details",
  4: "Rules & Regulations",
  5: "Upload Images",
  6: "Review & Submit",
};
